-- liquibase formatted sql
-- changeset Natalia:1
create table users
(
    id         bigint generated by default as identity        primary key,
    username   varchar(255),
    first_name varchar(255),
    last_name  varchar(255),
    password   varchar(255),
    phone      varchar(255),
    role       varchar(255),
    image	 varchar(255)
);

alter table users
    owner to graduate;

create table ad
(
    id          bigint generated by default as identity   primary key,
    description text,
    price       integer,
    title       varchar(255),
    image       varchar(255),
    FOREIGN KEY (id_user) REFERENCES user(id)
    on delete cascade
);

alter table users
    owner to graduate;

create table comments
(
    id          bigint generated by default as identity   primary key,
    created_at timestamp,
    text       text,
    FOREIGN KEY (id_user) REFERENCES users(id)
    FOREIGN KEY (id_ad) REFERENCES ad(id)
    on delete cascade
);

alter table users
    owner to graduate;
